meson: Check for __get_cpuid
checking for presence of cpuid.h header alone is not sufficient in some case to use
cpuid related functions. e.g. when using clang which is built for
multiple targets will have cpuid.h header as part of compiler headers in
distribution but one maybe compiling pulseaudion for non-x86 target. The
current check in meson succeeds and then compile fails later because
cpuid.h is x86-specific header. Therefore checking for symbol that is
needed makes this robust, so even if header exist it will try to ensure
the given symbol can be used

Fixes
src/pulsecore/core-util.c:113:
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/pulseaudio/14.0-r0/recipe-sysroot-native/usr/lib/clang/11.0.1/include/cpuid.h:11:2: error: this header is for x86 only
| #error this header is for x86 only
|  ^

Upstream-Status: Pending

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Tanu Kaskinen <tanuk@iki.fi>